apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kubernetes-project
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: FRONTEND/IMAGE
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 2345
            initialDelaySeconds: 60
            periodSeconds: 20


---

apiVersion: v1
kind: Service
metadata:
  namespace: kubernetes-project
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000
