apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kubernetes-project
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: YOUR_FRONTEND_IMAGE:TAG
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health  # Path to your frontend health check endpoint
              port: 3000      # Port on which your frontend server is listening
            initialDelaySeconds: 60  # Wait for 60 seconds before starting the probe
            periodSeconds: 20  # Check the health status every 20 seconds

---

apiVersion: v1
kind: Service
metadata:
  namespace: kubernetes-project
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000
